# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39d4cd94113486467e8229dde3b20980a3accc8fcc136186ef6f7ae22a1e1942c590e88738380bda6c8d0599bf5b17d5eb2b3d6ded0a48c96673363d3d6dcc05

test:
  secret_key_base: a89516ee2e173297fa26d9080c033098af0410ae6fbf5fc0aa8a509052f2ad07cb56cdc348f1c848d9a9be0b43206e2108192efd29d9c23c3e5140617b78625f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
